/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'loc' at '17.08.16 15:20' with Gradle 2.14.1
 *
 * @author loc, @date 17.08.16 15:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
